import type { WeeklyClientPack, MonthlyGovernancePack } from '@/lib/reports/clientPack'

/**
 * A print-ready screen for a weekly or monthly client pack — see
 * `docs/plans/2026-08-25-client-pack-design.md`. No PDF library, no headless browser: this is an
 * ordinary screen with a print stylesheet, and "download" is the browser's own print-to-PDF.
 *
 * Mounted as a full-screen overlay over the workspace (`.pack-scrim`), not the narrow `.modal`
 * used for dialogs elsewhere — a document this long needs the width, and `@media print` hides
 * everything outside `.pack-page` so only the report itself is ever printed.
 */

type Pack = WeeklyClientPack | MonthlyGovernancePack
function isWeekly(p: Pack): p is WeeklyClientPack {
  return 'lines' in p
}

export default function ClientPackView({ pack, onClose }: { pack: Pack; onClose: () => void }) {
  const weekly = isWeekly(pack)
  const title = weekly ? 'Weekly client pack' : 'Monthly governance pack'

  return (
    <div className="pack-scrim" role="dialog" aria-label={title}>
      <div className="pack-toolbar">
        <span>{title}</span>
        <span className="grow" />
        <button className="btn" onClick={() => window.print()}>
          Print / Save as PDF
        </button>
        <button className="btn" onClick={onClose}>
          Close
        </button>
      </div>
      <div className="pack-page">
        <h1>{title}</h1>
        <div className="pack-meta">
          <div>{pack.client}</div>
          <div>As of {pack.asOf}</div>
          <div>
            {weekly ? 'Activity' : 'Movement'} {pack.window.from} – {pack.window.to}
          </div>
        </div>

        {/*
         * The disclosure line — how many of the client's own records are actually shown here,
         * against how many exist. Stated plainly rather than left implicit: see the design
         * document's own reasoning for why a client reading "3 open issues" needs to know
         * whether that means a quiet engagement or an unmarked backlog.
         */}
        <p className="pack-disclosure">
          {pack.disclosure.shown} of {pack.disclosure.total} records for {pack.client} are shown
          here; the rest are marked internal.
        </p>

        <section>
          <h2>Position</h2>
          <div className="pack-position">
            <span>
              Open {pack.position.open} of {pack.position.total} ({pack.position.closed} closed)
            </span>
            <span>
              High {pack.position.high} · Medium {pack.position.medium} · Low {pack.position.low}
            </span>
          </div>
        </section>

        {weekly ? (
          <section>
            <h2>Activity this week</h2>
            {pack.lines.length === 0 ? (
              <p className="pack-empty">Nothing shown here had activity in this window.</p>
            ) : (
              <table className="pack-table">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Subject</th>
                    <th>Owner</th>
                    <th>Status</th>
                    <th>Severity</th>
                    <th>Due</th>
                    <th>Last activity</th>
                  </tr>
                </thead>
                <tbody>
                  {pack.lines.map((l) => (
                    <tr key={l.id}>
                      <td>{l.id}</td>
                      <td>{l.subject}</td>
                      <td>{l.owner}</td>
                      <td>{l.status}</td>
                      <td>{l.severity}</td>
                      <td>{l.due}</td>
                      <td>{l.lastActivity}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </section>
        ) : (
          <section>
            <h2>Movement this month</h2>
            {!pack.movement.trailAvailable ? (
              <p className="pack-empty">
                Nothing recorded. Movement is read from the audit trail, which is capped and, with
                no database configured, held in one browser — an empty section here means nothing
                was recorded in this trail, not that nothing happened.
              </p>
            ) : (
              <p>
                Raised {pack.movement.raised} · Resolved {pack.movement.resolved}
              </p>
            )}
          </section>
        )}

        <p className="pack-footer">
          Generated by Axiomate from {pack.disclosure.total} records for {pack.client}. Every
          figure is counted from the records or the audit trail; none is estimated.
        </p>
      </div>
    </div>
  )
}
