import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

/**
 * Prepare a local development environment.
 *
 * Run with `npm run db:setup`. It writes two files and applies nothing — the one step that
 * needs a superuser is left for a person to run, because a script that asks for a database
 * administrator's password is a script nobody should get in the habit of running.
 *
 * ---------------------------------------------------------------------------
 * What it generates, and why generating is the point
 *
 * A password, a session signing secret and a schedule token, all random. Every one of them is
 * a value a developer would otherwise invent, and invented ones are `postgres`, `changeme`, and
 * whatever the last project used — which is fine locally and stops being fine the first time a
 * local convention is copied into a deployment. Generating them means the weakest secret in the
 * project is 24 random bytes.
 *
 * Both files are gitignored. `.env` obviously; `db-setup.sql` less obviously, because it
 * carries the generated password, and a credential in a repository is a credential forever.
 * This generator is what belongs in version control.
 *
 * It never overwrites an existing `.env`. A developer who has put a real key in one should not
 * lose it to a setup script they ran twice.
 */

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')
const envPath = path.join(root, '.env')
const sqlPath = path.join(here, 'db-setup.sql')

const token = (bytes) => crypto.randomBytes(bytes).toString('base64url')

/* ---------------- .env ---------------- */

let password
if (fs.existsSync(envPath)) {
  const existing = fs.readFileSync(envPath, 'utf8')
  const found = existing.match(/^DATABASE_URL=postgresql:\/\/axiomate:([^@]+)@/m)
  password = found?.[1]
  console.log(
    password
      ? '.env already exists and names a password — reusing it, and leaving the file alone.'
      : '.env already exists but has no axiomate password in it. Left alone; edit it by hand.',
  )
} else {
  password = token(24)
  fs.writeFileSync(
    envPath,
    [
      '# Local development. Generated by `npm run db:setup`.',
      '# Gitignored. Nothing in here should ever be committed.',
      '',
      `DATABASE_URL=postgresql://axiomate:${password}@localhost:5432/axiomate_dev`,
      '',
      'AXIOMATE_TENANT=axiocloud',
      '# The name in the audit trail while there is no identity provider. Set it to yours.',
      'AXIOMATE_OPERATOR=',
      '',
      '# Signs the session cookie. Generated, and different in every environment.',
      `AXIOMATE_SESSION_SECRET=${token(48)}`,
      '',
      '# The scheduled pass: POST /api/schedule/run with this as a bearer token.',
      `AXIOMATE_SCHEDULE_TOKEN=${token(24)}`,
      '',
      '# Entra sign-in stays off until all four are set, and the app runs as the operator above.',
      'AXIOMATE_ENTRA_TENANT_ID=',
      'AXIOMATE_ENTRA_CLIENT_ID=',
      'AXIOMATE_ENTRA_CLIENT_SECRET=',
      'AXIOMATE_ENTRA_REDIRECT_URI=http://localhost:3000/api/auth/callback',
      '',
      '# Intake refuses everything while this is empty.',
      'AXIOMATE_INTAKE_TOKEN=',
      '',
      'ANTHROPIC_API_KEY=',
      '',
    ].join('\n'),
  )
  console.log('Written: .env')
}

/* ---------------- db-setup.sql ---------------- */

if (!password) {
  console.log('No password to write into the SQL. Fix .env first.')
  process.exit(1)
}

/*
 * Deliberately free of psql meta-commands. `\gexec` is the idiomatic way to make CREATE
 * DATABASE conditional and it is a single backslash that every layer of shell quoting between
 * here and the file wants to eat — so the role goes in a DO block, which is plain SQL, and the
 * database creation stands alone and errors harmlessly on a second run.
 */
const sql = [
  '-- Create the role and database Axiomate uses locally.',
  '--',
  '--   In SQL Shell (psql), which does NOT start in this directory — so an absolute path,',
  '--   forward slashes, quoted:',
  '--',
  "--     \\i 'C:/Axiomate-TMS/scripts/db-setup.sql'",
  '--',
  '--   Or from a shell already in the project:',
  '--',
  '--     psql -U postgres -f scripts/db-setup.sql',
  '--',
  "-- A dedicated role rather than reusing 'postgres': an application connecting as a superuser",
  '-- can drop anything on the server, and the day that matters is the day somebody points a',
  '-- migration at the wrong host.',
  '--',
  '-- Safe to run twice, and it sets the password every time rather than leaving an existing',
  '-- role alone. Leaving it alone is the tempting choice and it is the wrong one: this',
  '-- generator owns the password, .env already holds it, and a role quietly keeping an older',
  "-- one produces a failure that reads as 'wrong password' with nothing to compare against.",
  '--',
  '-- Written as two statements that each expect the other to have failed, rather than as a DO',
  '-- block. The block was tidier and used dollar quoting, which is one more thing for a shell',
  '-- to eat between here and psql — and this file has already lost a backslash that way. One of',
  '-- the two lines below always errors, harmlessly, and psql carries on: if the role exists the',
  '-- ALTER sets its password and the CREATE complains; if it does not, the reverse. Either way',
  '-- the role ends up with the password in .env.',
  '',
  `ALTER ROLE axiomate LOGIN PASSWORD '${password.replace(/'/g, "''")}';`,
  `CREATE ROLE axiomate LOGIN PASSWORD '${password.replace(/'/g, "''")}';`,
  '',
  '-- And the database, which likewise errors harmlessly if it is already there.',
  'CREATE DATABASE axiomate_dev OWNER axiomate;',
  '',
  '-- Proof that this file ran to the end, and against which server.',
  '--',
  '-- Every statement above errors harmlessly in one direction or the other, so a screen full',
  "-- of ERROR lines is the expected output and says nothing about whether the work was done.",
  '-- Worse, a file that was never found at all produces an error that looks much the same in',
  '-- a scrollback. This line only prints if execution reached it.',
  "SELECT 'db-setup ran. Role ' || rolname || ' exists, login=' || rolcanlogin",
  "       || ', on ' || inet_server_addr() || ':' || inet_server_port() AS result",
  "  FROM pg_roles WHERE rolname = 'axiomate';",
  '',
].join('\n')

fs.writeFileSync(sqlPath, sql)
console.log('Written: scripts/db-setup.sql')
console.log('')
console.log('Next, as a database superuser, from this directory:')
console.log('  psql -U postgres -f scripts/db-setup.sql')
console.log('')
console.log('One of the two role statements will report an error. That is expected: they are')
console.log('written so that whichever one does not apply fails harmlessly.')
console.log('')
console.log('Then:')
console.log('  npm run db:migrate        apply the schema')
console.log('  npm run audit:persistence prove a write survives the round trip')
console.log('  npm run dev               and the workspace saves to Postgres')
